# Generated by Django 4.0.3 on 2022-03-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('betroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.realtor')),
            ],
        ),
    ]
