# Generated by Django 4.0.3 on 2022-03-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
        ('listing', '0003_rename_betroom_listing_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='realtor.realtor'),
        ),
        migrations.AlterField(
            model_name='listing_images',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingImages', to='listing.listing'),
        ),
    ]
